### ISSUE TITLE
conesearch 

### ISSUE THREAD

**Issue by lyang54** [chbrandt/eada#7]
Hi, 
I was try to use VOU_Blazars to search for sources. However, it looks the conesearch cannot work well, as seen below. Could you please help with this? Appreciate for your help.

(eada) liliyang@x86_64-apple-darwin13 VOU_Blazars % conesearch --db bin/cats1.ini --catalog FIRST --ra 153.76 --dec 49.43 --radius 20 --runit arcmin --columns default
Traceback (most recent call last):
  File "/Users/liliyang/opt/anaconda3/envs/eada/bin/conesearch", line 189, in <module>
    cp = config._read(args.dbfile)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/eada/io/config.py", line 56, in _read
    cfg_ = config.read_ini(filename)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/eada/io/config.py", line 139, in read_ini
    for k,v in config.items(_section):
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/backports/configparser/__init__.py", line 870, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/backports/configparser/__init__.py", line 867, in <lambda>
    section, option, d[option], d)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/backports/configparser/__init__.py", line 387, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/backports/configparser/__init__.py", line 437, in _interpolate_some
    "found: %r" % (rest,))
backports.configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%2F92%2Ffirst14'

**Comment by lyang54** [comment]
The above issue was solved, but a new one is coming...


(eada) liliyang@x86_64-apple-darwin13 VOU_Blazars % conesearch --db bin/cats1.ini --catalog FIRST --ra 153.76 --dec 49.43 --radius 20 --runit arcmin --columns default
Traceback (most recent call last):
  File "/Users/liliyang/opt/anaconda3/envs/eada/bin/conesearch", line 234, in <module>
    table = cs.main(ra,dec,radius,url,cols)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/eada/vo/conesearch.py", line 138, in main
    cols = Aux.filter_columns(tab,columns)
  File "/Users/liliyang/opt/anaconda3/envs/eada/lib/python2.7/site-packages/eada/vo/conesearch.py", line 42, in filter_columns
    assert(isinstance(col,str))
AssertionError
